/**
 * sokoban-utils
 *
 * Thin TypeScript wrapper around the WASM module.
 *
 * The WASM layer (in `pkg/`) is generated by `wasm-pack` from the Rust crate.
 * This file re-exports everything and adds the URL encoding helpers that live
 * in TS (base64url via native APIs) as an alternative to the Rust path.
 *
 * Usage:
 *   import { init, SokobanLevel, Solver, levelToFragment, fragmentToLevel } from '@thequirkyfox/sokoban-utils'
 *   await init()
 *   const level = SokobanLevel.from_xsb(xsbString)
 */

// The WASM package is generated into `pkg/` by wasm-pack.
// Adjust this path if you rename the output directory in package.json#scripts.
import init, {
  SokobanLevel,
  Solver,
  SolverResult,
  level_to_fragment,
  fragment_to_level,
  fragment_metadata,
} from '../pkg/sokoban_utils.js';

export type { SolverResult };
export { SokobanLevel, Solver };

// ── Init ──────────────────────────────────────────────────────────────────

let _initialised = false;

/**
 * Initialise the WASM module. Must be awaited before calling anything else.
 * Safe to call multiple times — subsequent calls are no-ops.
 */
export async function initWasm(): Promise<void> {
  if (_initialised) return;
  await init();
  _initialised = true;
}

// ── URL helpers ───────────────────────────────────────────────────────────

export interface LevelMetadata {
  title?: string;
  author?: string;
}

/**
 * Encode a level into a URL fragment string (`v1-...`).
 * Delegates to the Rust implementation for consistency with `fragmentToLevel`.
 */
export function levelToFragment(
  level: SokobanLevel,
  meta?: LevelMetadata,
): string {
  return level_to_fragment(level, meta?.title ?? undefined, meta?.author ?? undefined);
}

/**
 * Decode a URL fragment (with or without leading `#`) back to a level.
 */
export function fragmentToLevel(fragment: string): SokobanLevel {
  return fragment_to_level(fragment);
}

/**
 * Extract metadata from a fragment without fully decoding the level.
 */
export function getFragmentMetadata(fragment: string): LevelMetadata {
  const raw = fragment_metadata(fragment) as Record<string, string>;
  return {
    title: raw['title'],
    author: raw['author'],
  };
}

// ── Native base64url helpers (TS-side, for use outside the WASM boundary) ──

/**
 * Encode a Uint8Array to base64url (no padding).
 * Uses the native `btoa` available in browsers and Node ≥ 16.
 */
export function toBase64Url(bytes: Uint8Array): string {
  const binary = Array.from(bytes, (b) => String.fromCharCode(b)).join('');
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

/**
 * Decode a base64url string (no padding required) to a Uint8Array.
 */
export function fromBase64Url(str: string): Uint8Array {
  const padded = str.replace(/-/g, '+').replace(/_/g, '/');
  const binary = atob(padded);
  return Uint8Array.from(binary, (c) => c.charCodeAt(0));
}

// ── Convenience: sync solve ───────────────────────────────────────────────

export interface SolveOptions {
  /** Maximum push-states to explore before giving up. Default: 500_000 */
  maxNodes?: number;
  /**
   * Let the solver discover deadlock sets while searching. Default: false.
   *
   * It is sound, but currently costs far more than it saves: across the
   * 100-puzzle sample it changed no outcome and no push count while taking
   * 7.5x as long. Turn it on only when experimenting with that engine.
   */
  dynamicDeadlocks?: boolean;
}

export interface SolveResult {
  solved: boolean;
  /** Number of box pushes in the solution. */
  pushCount: number;
  /**
   * Push sequence as flat array: [fromX, fromY, toX, toY, ...].
   * Empty if unsolved.
   */
  pushes: number[];
  /**
   * Full solution in LURD format. Lowercase letters are player walk steps,
   * uppercase letters are box pushes.
   *   u/U = up, d/D = down, l/L = left, r/R = right
   * Empty string if unsolved.
   *
   * Example: "rruLLddR" — player walks right twice, then pushes box left twice, etc.
   * You can drive a renderer step-by-step by iterating each character.
   */
  moves: string;
}

/**
 * Solve a level synchronously.
 *
 * For levels that take >~100ms, consider running this in a Web Worker so the
 * main thread stays responsive.
 */
export function solveLevel(level: SokobanLevel, options?: SolveOptions): SolveResult {
  const solver = Solver.new(level);
  solver.set_dynamic_deadlocks(options?.dynamicDeadlocks ?? false);
  const result = solver.solve(level, options?.maxNodes ?? 500_000);
  return {
    solved: result.solved(),
    pushCount: result.push_count(),
    pushes: Array.from(result.pushes()),
    moves: result.moves(),
  };
}
